import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-api-key",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Authenticate via X-API-KEY header (service role key or a custom server key)
    const apiKey = req.headers.get("x-api-key");
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    
    if (!apiKey || apiKey !== serviceRoleKey) {
      return new Response(
        JSON.stringify({ error: "Unauthorized" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabase = createClient(supabaseUrl, serviceRoleKey!);

    const url = new URL(req.url);
    const path = url.pathname.split("/").filter(Boolean);
    // Path: /firewall-sync or /firewall-sync/{ip_address}
    
    const ipFilter = url.searchParams.get("ip");
    const userId = url.searchParams.get("user_id");
    const format = url.searchParams.get("format") || "json"; // json or iptables

    let query = supabase
      .from("firewall_rules")
      .select("*")
      .eq("enabled", true)
      .order("priority", { ascending: true });

    if (ipFilter) {
      query = query.or(`destination_ip.eq.${ipFilter},source_ip.eq.${ipFilter}`);
    }
    if (userId) {
      query = query.eq("user_id", userId);
    }

    const { data: rules, error } = await query;
    if (error) throw error;

    if (format === "iptables") {
      const lines = [
        "# Generated by Hoxta Firewall Manager",
        `# Date: ${new Date().toISOString()}`,
        `# Rules: ${rules.length}`,
        "*filter",
        ":INPUT ACCEPT [0:0]",
        ":FORWARD ACCEPT [0:0]",
        ":OUTPUT ACCEPT [0:0]",
        "",
      ];

      for (const rule of rules) {
        let line = `iptables -A ${rule.direction}`;
        line += ` -p ${rule.protocol}`;
        
        if (rule.source_ip && rule.source_ip !== "0.0.0.0/0") {
          line += ` -s ${rule.source_ip}`;
        }
        if (rule.destination_ip && rule.destination_ip !== "0.0.0.0/0") {
          line += ` -d ${rule.destination_ip}`;
        }
        if (rule.port) {
          line += ` --dport ${rule.port}`;
        } else if (rule.port_range) {
          line += ` --dport ${rule.port_range}`;
        }
        line += ` -j ${rule.action}`;
        if (rule.label) {
          line += ` # ${rule.label}`;
        }
        lines.push(line);
      }

      lines.push("", "COMMIT");

      return new Response(lines.join("\n"), {
        headers: { ...corsHeaders, "Content-Type": "text/plain" },
      });
    }

    return new Response(
      JSON.stringify({
        count: rules.length,
        generated_at: new Date().toISOString(),
        rules: rules.map((r) => ({
          id: r.id,
          direction: r.direction,
          protocol: r.protocol,
          source_ip: r.source_ip,
          destination_ip: r.destination_ip,
          port: r.port,
          port_range: r.port_range,
          action: r.action,
          priority: r.priority,
          label: r.label,
          notes: r.notes,
        })),
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
